default_language_version:
  python: python3
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: .py$
  - repo: https://github.com/python/black
    rev: 21.9b0
    hooks:
      - id: black
        files: .py$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "88"]
        files: .py$
